[package]
name = "simple_blockchain_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2="0.10.9"
hex-literal = "1.0.0"
serde = {version="1.0.219", features = ["derive"]}
chrono = "0.4.41"
serde_json = "1.0.140"
bincode = "2.0.1"
hex = "0.4.3"